import {
  Building2,
  Boxes,
  Building,
  Calculator,
  CalendarRange,
  ChartColumn,
  CookingPot,
  ClipboardList,
  Database,
  FileCheck,
  Fence,
  Fuel,
  Footprints,
  Globe,
  HandCoins,
  HandHeart,
  HeartHandshake,
  History,
  Home,
  Hospital,
  Languages,
  Landmark,
  LayoutDashboard,
  Megaphone,
  Map,
  MapPin,
  MessageSquare,
  Milestone,
  Package,
  PackageCheck,
  Pill,
  PackageOpen,
  ScrollText,
  Snowflake,
  Route,
  Scale,
  ScanSearch,
  Send,
  Settings,
  Shield,
  Stamp,
  Store,
  Tags,
  Tent,
  Ticket,
  UserCog,
  UserRound,
  UserRoundCog,
  UserRoundCheck,
  Users,
  UsersRound,
  UtensilsCrossed,
  Wallet,
  Wheat,
  Newspaper,
  type LucideIcon,
} from 'lucide-react'

const icons: Record<string, LucideIcon> = {
  'layout-dashboard': LayoutDashboard,
  home: Home,
  users: Users,
  'users-round': UsersRound,
  footprints: Footprints,
  tent: Tent,
  'user-cog': UserCog,
  'user-round-check': UserRoundCheck,
  'user-round-cog': UserRoundCog,
  'message-square': MessageSquare,
  settings: Settings,
  send: Send,
  'clipboard-list': ClipboardList,
  database: Database,
  globe: Globe,
  fence: Fence,
  map: Map,
  'map-pin': MapPin,
  route: Route,
  scale: Scale,
  'scan-search': ScanSearch,
  building: Building,
  'building-2': Building2,
  boxes: Boxes,
  calculator: Calculator,
  'calendar-range': CalendarRange,
  'cooking-pot': CookingPot,
  'chart-column': ChartColumn,
  'utensils-crossed': UtensilsCrossed,
  hospital: Hospital,
  fuel: Fuel,
  pill: Pill,
  shield: Shield,
  tags: Tags,
  'hand-coins': HandCoins,
  'heart-handshake': HeartHandshake,
  history: History,
  'hand-heart': HandHeart,
  landmark: Landmark,
  megaphone: Megaphone,
  milestone: Milestone,
  languages: Languages,
  package: Package,
  'package-check': PackageCheck,
  'package-open': PackageOpen,
  'scroll-text': ScrollText,
  snowflake: Snowflake,
  stamp: Stamp,
  'file-check': FileCheck,
  store: Store,
  ticket: Ticket,
  newspaper: Newspaper,
  'user-round': UserRound,
  wallet: Wallet,
  wheat: Wheat,
}

export function getNavIcon(name: string): LucideIcon {
  return icons[name] ?? LayoutDashboard
}
