import type { NavModule } from '../types/app'

export const APP_NAV: NavModule[] = [
  {
    code: 'dashboard',
    nameKey: 'modules.dashboard',
    icon: 'layout-dashboard',
    sortOrder: 1,
    menus: [
      {
        code: 'dashboard.home',
        nameKey: 'menus.overview',
        path: '/',
        icon: 'layout-dashboard',
        sortOrder: 1,
      },
      {
        code: 'dashboard.users',
        nameKey: 'menus.users',
        path: '/users',
        icon: 'users',
        sortOrder: 2,
      },
    ],
  },
  {
    code: 'base-info',
    nameKey: 'modules.baseInfo',
    icon: 'globe',
    sortOrder: 2,
    menus: [
      {
        code: 'base-info.countries',
        nameKey: 'menus.countries',
        path: '/base-info/countries',
        icon: 'globe',
        sortOrder: 1,
      },
      {
        code: 'base-info.provinces',
        nameKey: 'menus.provinces',
        path: '/base-info/provinces',
        icon: 'map',
        sortOrder: 2,
      },
      {
        code: 'base-info.cities',
        nameKey: 'menus.cities',
        path: '/base-info/cities',
        icon: 'map-pin',
        sortOrder: 3,
      },
    ],
  },
  {
    code: 'projects',
    nameKey: 'modules.projects',
    icon: 'folder-kanban',
    sortOrder: 3,
    menus: [
      {
        code: 'projects.list',
        nameKey: 'menus.projects',
        path: '/projects',
        icon: 'folder-kanban',
        sortOrder: 1,
      },
      {
        code: 'projects.reports',
        nameKey: 'menus.projectReports',
        path: '/projects/reports',
        icon: 'chart-column',
        sortOrder: 2,
      },
    ],
  },
  {
    code: 'food-reservation',
    nameKey: 'modules.foodReservation',
    icon: 'cooking-pot',
    sortOrder: 4,
    menus: [
      {
        code: 'food-reservation.foods',
        nameKey: 'menus.foodManagement',
        path: '/food-reservation/foods',
        icon: 'utensils-crossed',
        sortOrder: 1,
      },
      {
        code: 'food-reservation.restaurants',
        nameKey: 'menus.restaurantManagement',
        path: '/food-reservation/restaurants',
        icon: 'store',
        sortOrder: 2,
      },
      {
        code: 'food-reservation.reserve',
        nameKey: 'menus.foodReserve',
        path: '/food-reservation/reserve/new',
        icon: 'ticket',
        sortOrder: 3,
      },
      {
        code: 'food-reservation.history',
        nameKey: 'menus.foodReservationHistory',
        path: '/food-reservation/history',
        icon: 'history',
        sortOrder: 4,
      },
      {
        code: 'food-reservation.report',
        nameKey: 'menus.foodReservationReport',
        path: '/food-reservation/report',
        icon: 'chart-column',
        sortOrder: 5,
      },
    ],
  },
  {
    code: 'qeshm-organization',
    nameKey: 'modules.qeshmOrganization',
    icon: 'landmark',
    sortOrder: 5,
    menus: [
      {
        code: 'qeshm-organization.info',
        nameKey: 'menus.organization',
        path: '/organization',
        icon: 'landmark',
        sortOrder: 1,
      },
      {
        code: 'qeshm-organization.positions',
        nameKey: 'menus.organizationPositions',
        path: '/organization/positions',
        icon: 'clipboard-list',
        sortOrder: 2,
      },
      {
        code: 'qeshm-organization.units',
        nameKey: 'menus.organizationUnits',
        path: '/organization/units',
        icon: 'building-2',
        sortOrder: 3,
      },
      {
        code: 'qeshm-organization.employees',
        nameKey: 'menus.organizationEmployees',
        path: '/organization/employees',
        icon: 'users',
        sortOrder: 4,
      },
    ],
  },
]
